services:

  core:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.12.3

        RUN mkdir -p /usr/src
        COPY ./src /usr/src
        COPY ./pyproject.toml /usr/pyproject.toml

        WORKDIR /usr

        RUN python -m pip install uv

        RUN pip install uv
        RUN uv pip install --system .

        CMD ["uvicorn", "src.main:app", "--port", "8001"]

    container_name: fastapi_server
    restart: unless-stopped
    ports:
      - "8001:${FLASK_PORT}"
    environment:
      LOG_LEVEL: ${LOG_LEVEL}